### ISSUE TITLE
java.lang.ClassNotFoundException: com.bazaarvoice.maven.plugin.process.CrossMojoState

### ISSUE THREAD

**Issue by arauchberger** [bazaarvoice/maven-process-plugin#46]
Hi,
this might be a duplicate of #24 but i don't really see the solving. adding the goals "clean verify" did not give me any improvement on this.

i tried version 0.7-0.9 of the plugin. i checked my local maven-repo for the plugin (removed, re-downloaded, inspected) everything looks ok.

the error that occurs is:
```
[ERROR] Failed to execute goal com.bazaarvoice.maven.plugins:process-exec-maven-plugin:0.7:start (start-pine-micro-service) on project fhirstore-netty: Execution start-pine-micro-service of goal com.bazaarvoice.maven.plugins:process-exec-maven-plugin:0.7:start failed.: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Exception in thread "Thread-6" java.lang.NoClassDefFoundError: com/bazaarvoice/maven/plugin/process/CrossMojoState
	at com.bazaarvoice.maven.plugin.process.AbstractProcessMojo$1.run(AbstractProcessMojo.java:61)
Caused by: java.lang.ClassNotFoundException: com.bazaarvoice.maven.plugin.process.CrossMojoState
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 1 more
```

hope there is a simple solution to help me out.
thanks in advance

**Comment by Ruchira-R** [comment]
Hi, did you fin out a way to fix this @arauchberger? Any help is appreciated. Thanks

**Comment by arauchberger** [comment]
hi,

i don't use this plugin anymore.

sorry

**Comment by sdoeringNew** [comment]
I got rid of this message by simply adding a stop-all execution after the initial start execution.

    <execution>
        <id>stop-all</id>
        <phase>post-integration-test</phase>
        <goals>
            <goal>stop-all</goal>
        </goals>
    </execution>
